# Styleguide settings
# 'site' variables
sg_title: Welt Living Styleguide
sg_version: 1.0
sg_description: This is the Living Styleguide welt.de.
sg_language: en
sg_styles: /styleguide/css/styleguide.css
sg_favicon: /styleguide/static/favicon.ico

destination: _site

# Collections
collections:
  docs:
    output: true

defaults:
  -
    scope:
      path: "_docs"
    values:
      layout: default
      type: doc
      maturity: "Proposed"
      scss: "Not Assigned"
  -
    scope:
      path: "_docs/branding"
    values:
      layout: index
      type: "branding"